#! /bin/bash
echo ""
echo "Navigate to `ipconfig getifaddr en0`:8000 on your phone"
ssid="`/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport -I | awk '/ SSID/ {print substr($0, index($0, $2))}'`"
echo "Be sure your phone is connected to $ssid"
echo ""
python -m SimpleHTTPServer

